- name: config frontend
  hosts: frontend
  become: yes
  tasks:
  - name: install NGINX
    ansible.builtin.package:
      name: nginx
      state: present

  - name: run nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

  - name: remove directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent
  
  - name: create html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory
  
  - name: downlaod front end code
    ansibe.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /tmp/frontend.zip

  - name: extract the fromend code
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html
      remote_src: yes
  
  - name: copy frontend service
    ansible.builtin.copy: 
      src: expense.conf
      dest: /etc/nginx/default.d/expense.conf

  - name: restart the nginx
    ansible.builtin.service:
      name: nginx
      state: restarted