- name: My SQL server config
  hosts: mysql
  become: yes
  vars:
    mysql_root_password: ExpenseApp1
    login_host: mysql.ravijavadevops.site
  tasks:
  - name: ansible to install boto3 and botocore
    ansible.builtin.pip:
      name:
      - PyMySQL
      executable: pip3.9
  - name: create my sql server
    ansible.builtin.package:
      name: mysql-server
      state: present
  - name: start mysql server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: connect MySql 
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{ mysql_root_password }}"
      login_host: "{{ login_host }}"
    ignore_errors: true
    register: mysql_info

  - name: print my sql info
    ansible.builtin.debug:
      msg: "{{ mysql_info }}"
